In [1]:
import sqlite3
import pandas as pd

df_clean = pd.read_csv("../data/processed/online_retail_cleaned.csv", parse_dates=["InvoiceDate"])

conn = sqlite3.connect("../data/processed/retail_analysis.db")
df_clean.to_sql("fact_sales", conn, if_exists="replace", index=False)

print("Table loaded into SQLite successfully")

Table loaded into SQLite successfully

In [2]:
pd.read_sql("SELECT * FROM fact_sales LIMIT 5;", conn)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,CustomerID,Country,Revenue
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,30.0

In [7]:
top_products_query = """
SELECT StockCode, Description, SUM(Revenue) AS total_revenue
FROM fact_sales
GROUP BY StockCode, Description
ORDER BY total_revenue DESC
LIMIT 10;
"""

pd.read_sql(top_products_query, conn)

  StockCode                         Description  total_revenue
0     22423            REGENCY CAKESTAND 3 TIER      286486.30
1    85123A  WHITE HANGING HEART T-LIGHT HOLDER      252072.46
2     23843         PAPER CRAFT , LITTLE BIRDIE      168469.60
3         M                              Manual      152340.57
4    85099B             JUMBO BAG RED RETROSPOT      136980.08
5     84879       ASSORTED COLOUR BIRD ORNAMENT      127074.17
6      POST                             POSTAGE      126563.04
7     47566                       PARTY BUNTING      103880.23
8     23166      MEDIUM CERAMIC TOP STORAGE JAR       81416.73
9     22086     PAPER CHAIN KIT 50'S CHRISTMAS        79594.33

In [9]:
top_customers_query = """
SELECT CustomerID, SUM(Revenue) AS total_spent
FROM fact_sales
GROUP BY CustomerID
ORDER BY total_spent DESC
LIMIT 10;
"""

pd.read_sql(top_customers_query, conn)

   CustomerID  total_spent
0       18102    608821.65
1       14646    528602.52
2       14156    313946.37
3       14911    295972.63
4       17450    246973.09
5       13694    196482.81
6       17511    175603.55
7       16446    168472.50
8       16684    147142.77
9       12415    144458.37

In [12]:
monthly_sales_query = """
SELECT strftime('%Y-%m', InvoiceDate) AS sales_month,
       SUM(Revenue) AS monthly_revenue,
       COUNT(*) AS order_lines
FROM fact_sales
GROUP BY sales_month
ORDER BY sales_month;
"""
pd.read_sql(monthly_sales_query, conn)

   sales_month  monthly_revenue  order_lines
0      2009-12       686654.160        30754
1      2010-01       557319.062        21775
2      2010-02       506371.066        23367
3      2010-03       699608.991        32301
4      2010-04       594609.192        27235
5      2010-05       599985.790        28644
6      2010-06       639066.580        31188
7      2010-07       591636.740        27032
8      2010-08       604242.650        26392
9      2010-09       831615.001        34599
10     2010-10      1036680.000        49561
11     2010-11      1172336.042        60312
12     2010-12       884591.890        40661
13     2011-01       569445.040        21229
14     2011-02       447137.350        19927
15     2011-03       595500.760        27175
16     2011-04       469200.361        22642
17     2011-05       678594.560        28320
18     2011-06       661213.690        27185
19     2011-07       600091.011        26825
20     2011-08       645343.900        27007
21     2011-09       952838.382        40028
22     2011-10      1039318.790        49554
23     2011-11      1161817.380        64531
24     2011-12       518210.790        17305

In [14]:
revenue_share_by_product = """
SELECT Description,
       SUM(Revenue) AS total_revenue,
       ROUND(100.0 * SUM(Revenue) / (SELECT SUM(Revenue) FROM fact_sales), 2) AS revenue_share_pct
FROM fact_sales
GROUP BY Description
ORDER BY total_revenue DESC
LIMIT 10;
"""

pd.read_sql(revenue_share_by_product, conn)

                          Description  total_revenue  revenue_share_pct
0            REGENCY CAKESTAND 3 TIER      286486.30               1.61
1  WHITE HANGING HEART T-LIGHT HOLDER      252072.46               1.42
2         PAPER CRAFT , LITTLE BIRDIE      168469.60               0.95
3                              Manual      152340.57               0.86
4             JUMBO BAG RED RETROSPOT      136980.08               0.77
5       ASSORTED COLOUR BIRD ORNAMENT      127074.17               0.72
6                             POSTAGE      126563.04               0.71
7                       PARTY BUNTING      103880.23               0.59
8      MEDIUM CERAMIC TOP STORAGE JAR       81416.73               0.46
9     PAPER CHAIN KIT 50'S CHRISTMAS        79594.33               0.45

In [17]:
monthly_average_order_value = """
WITH monthly_customer AS (
    SELECT strftime('%Y-%m', InvoiceDate) AS sales_month,
           CustomerID,
           SUM(Revenue) AS customer_month_revenue
    FROM fact_sales
    GROUP BY sales_month, CustomerID
)
SELECT sales_month,
       ROUND(AVG(customer_month_revenue), 2) AS avg_customer_month_revenue
FROM monthly_customer
GROUP BY sales_month
ORDER BY sales_month;
"""
pd.read_sql(monthly_average_order_value, conn)

   sales_month  avg_customer_month_revenue
0      2009-12                      719.01
1      2010-01                      774.05
2      2010-02                      655.92
3      2010-03                      661.88
4      2010-04                      631.22
5      2010-05                      621.10
6      2010-06                      613.90
7      2010-07                      637.54
8      2010-08                      663.27
9      2010-09                      726.30
10     2010-10                      692.51
11     2010-11                      729.52
12     2010-12                      999.54
13     2011-01                      768.48
14     2011-02                      589.89
15     2011-03                      611.40
16     2011-04                      548.13
17     2011-05                      642.61
18     2011-06                      667.22
19     2011-07                      632.34
20     2011-08                      690.21
21     2011-09                      752.64
22     2011-10                      761.96
23     2011-11                      698.21
24     2011-12                      842.62

In [21]:
Customer_concentration = """
WITH customer_totals AS (
    SELECT CustomerID, SUM(Revenue) AS total_spent
    FROM fact_sales
    GROUP BY CustomerID
),
threshold AS (
    SELECT AVG(total_spent) AS avg_spent
    FROM customer_totals
)
SELECT 
    CASE 
        WHEN total_spent >= (SELECT avg_spent FROM threshold) THEN 'Above average spenders'
        ELSE 'Below average spenders'
    END AS customer_group,
    COUNT(*) AS customers,
    ROUND(SUM(total_spent), 2) AS revenue
FROM customer_totals
GROUP BY customer_group
ORDER BY revenue DESC;
"""

pd.read_sql(Customer_concentration, conn)

           customer_group  customers      revenue
0  Above average spenders       1151  13633584.23
1  Below average spenders       4727   4109844.95

In [22]:
avg_spend_query = """
SELECT ROUND(SUM(Revenue) / COUNT(DISTINCT CustomerID), 2) AS avg_spend_per_customer
FROM fact_sales;
"""

pd.read_sql(avg_spend_query, conn)

   avg_spend_per_customer
0                 3018.62

In [23]:
pd.read_sql("PRAGMA table_info(fact_sales);", conn)

   cid         name       type  notnull dflt_value  pk
0    0      Invoice    INTEGER        0       None   0
1    1    StockCode       TEXT        0       None   0
2    2  Description       TEXT        0       None   0
3    3     Quantity    INTEGER        0       None   0
4    4  InvoiceDate  TIMESTAMP        0       None   0
5    5        Price       REAL        0       None   0
6    6   CustomerID    INTEGER        0       None   0
7    7      Country       TEXT        0       None   0
8    8      Revenue       REAL        0       None   0

In [24]:
region_revenue = """
SELECT Country,
       SUM(Revenue) AS total_revenue,
       COUNT(DISTINCT CustomerID) AS customers
FROM fact_sales
GROUP BY Country
ORDER BY total_revenue DESC;
"""
pd.read_sql(region_revenue, conn)

                 Country  total_revenue  customers
0         United Kingdom   1.472315e+07       5350
1                   EIRE   6.216311e+05          5
2            Netherlands   5.542323e+05         22
3                Germany   4.312625e+05        107
4                 France   3.552575e+05         95
5              Australia   1.699681e+05         15
6                  Spain   1.091785e+05         41
7            Switzerland   1.003653e+05         22
8                 Sweden   9.154972e+04         19
9                Denmark   6.986219e+04         12
10               Belgium   6.575342e+04         29
11                Norway   6.010962e+04         13
12              Portugal   5.728530e+04         24
13                 Japan   4.713839e+04         10
14       Channel Islands   4.499676e+04         13
15                 Italy   3.255042e+04         17
16               Finland   2.992554e+04         14
17             Singapore   2.531706e+04          1
18                Cyprus   2.498013e+04         11
19               Austria   2.361301e+04         13
20                Greece   1.909619e+04          5
21                Poland   1.090245e+04          6
22                Israel   1.042109e+04          4
23  United Arab Emirates   9.202690e+03          4
24           Unspecified   8.613650e+03          6
25                   USA   8.366860e+03          9
26                 Malta   8.099090e+03          2
27             Lithuania   6.553740e+03          1
28               Iceland   5.633320e+03          1
29                Canada   4.883040e+03          5
30              Thailand   3.070540e+03          1
31                   RSA   1.933740e+03          2
32               Lebanon   1.693880e+03          1
33                Brazil   1.411870e+03          2
34               Bahrain   1.354370e+03          2
35    European Community   1.300250e+03          1
36                 Korea   1.118510e+03          2
37        Czech Republic   8.267400e+02          1
38           West Indies   5.364100e+02          1
39          Saudi Arabia   1.459200e+02          1
40               Nigeria   1.403900e+02          1

In [25]:
avg_customer_spend_country = """
WITH customer_country_spend AS (
    SELECT Country,
           CustomerID,
           SUM(Revenue) AS customer_spent
    FROM fact_sales
    GROUP BY Country, CustomerID
)
SELECT Country,
       ROUND(AVG(customer_spent), 2) AS avg_customer_spent,
       COUNT(*) AS customers
FROM customer_country_spend
GROUP BY Country
ORDER BY avg_customer_spent DESC;
"""

df_avg_country = pd.read_sql(avg_customer_spend_country, conn)
df_avg_country

                 Country  avg_customer_spent  customers
0                   EIRE           124326.22          5
1              Singapore            25317.06          1
2            Netherlands            25192.38         22
3              Australia            11331.21         15
4              Lithuania             6553.74          1
5                Denmark             5821.85         12
6                Iceland             5633.32          1
7                 Sweden             4818.41         19
8                  Japan             4713.84         10
9                 Norway             4623.82         13
10           Switzerland             4562.06         22
11                 Malta             4049.55          2
12               Germany             4030.49        107
13                Greece             3819.24          5
14                France             3739.55         95
15       Channel Islands             3461.29         13
16              Thailand             3070.54          1
17        United Kingdom             2751.99       5350
18                 Spain             2662.89         41
19                Israel             2605.27          4
20              Portugal             2386.89         24
21  United Arab Emirates             2300.67          4
22                Cyprus             2270.92         11
23               Belgium             2267.36         29
24               Finland             2137.54         14
25                 Italy             1914.73         17
26                Poland             1817.08          6
27               Austria             1816.39         13
28               Lebanon             1693.88          1
29           Unspecified             1435.61          6
30    European Community             1300.25          1
31                Canada              976.61          5
32                   RSA              966.87          2
33                   USA              929.65          9
34        Czech Republic              826.74          1
35                Brazil              705.93          2
36               Bahrain              677.18          2
37                 Korea              559.25          2
38           West Indies              536.41          1
39          Saudi Arabia              145.92          1
40               Nigeria              140.39          1